# This is a GitHub Actions workflow for CI/CD in 2023.

# The workflow is triggered when there are pushes to the 'master' branch and pull requests.
name: CI devops 2023
on:
  # Trigger the workflow on pushes to the 'master' branch.
  push:
    branches:
      - main
  # Also, trigger the workflow on pull requests.

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Check out your GitHub code using actions/checkout@v2.4.2.
      - uses: actions/checkout@v2.4.2

      # Step 2: Set up JDK 17 using actions/setup-java@v3.
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"      # Specify the Java distribution to use (e.g., AdoptOpenJDK).
          java-version: "17"         # Specify the Java version (e.g., Java 17).

      # Step 3: Build your app with the 'mvn clean verify' command.
      - name: Build and test with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=theogenix_devOps -Dsonar.organization=sonarcloudtheogenix -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml

        working-directory: backend/simpleapi/simple-api-student  # Set the working directory for the Maven build.

  # Define a job to build and push Docker images.
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: backend/simpleapi/simple-api-student
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{secrets.DOCKER_USERNAME}}/tp-devops-simple-api-backend:latest

      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: database
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{secrets.DOCKER_USERNAME}}/tp-devops-simple-api-database:latest

      - name: Build and push httpd image
        uses: docker/build-push-action@v3
        with:
          context: http
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{secrets.DOCKER_USERNAME}}/tp-devops-simple-api-httpd:latest
